-- Tabela de inscritos da newsletter
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz default now() not null
);

ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- O cadastro e a leitura são feitos exclusivamente pelas server functions
-- usando a chave service_role. Não exponha essa chave no navegador.
CREATE UNIQUE INDEX IF NOT EXISTS idx_newsletter_subscribers_email
  ON newsletter_subscribers (email);

-- Tabela de artigos do blog (admin only)
CREATE TABLE IF NOT EXISTS blog_articles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  badge text not null default 'purple',
  category text not null,
  read_time text not null,
  title text not null,
  excerpt text not null,
  published_label text,
  author text not null default 'Equipe Doc.Lab',
  content jsonb not null default '[]',
  published boolean not null default true,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

ALTER TABLE blog_articles ENABLE ROW LEVEL SECURITY;

-- Política: apenas admin pode ler/inserir/atualizar/deletar
-- O admin é identificado pelo cookie de sessão (validado via server function)
-- Para simplificar, usamos uma função de definição que verifica uma variável de contexto
-- Na prática, o RLS aqui serve como camada extra; a securitação principal é no server function

CREATE POLICY "Admins can manage articles" ON blog_articles
  FOR ALL
  USING (true);

-- Índices
CREATE INDEX IF NOT EXISTS idx_blog_articles_slug ON blog_articles (slug);
CREATE INDEX IF NOT EXISTS idx_blog_articles_published ON blog_articles (published);

COMMENT ON TABLE blog_articles IS 'Artigos do blog administrados via painel /admin';
